FROM golang:1.23-alpine AS builder

RUN apk add --no-cache git ca-certificates

WORKDIR /app

COPY ContestManager/go.mod ContestManager/go.sum ./
RUN go mod download

COPY ContestManager/internal ./internal
COPY ContestManager/api ./api
COPY ContestManager/cmd ./cmd

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 GOOS=linux go build \
    -ldflags='-w -s' \
    -o worker ./cmd/worker

FROM alpine:latest

RUN apk add --no-cache ca-certificates docker-cli g++ python3

WORKDIR /root/

COPY --from=builder /app/worker .

RUN mkdir -p /tmp/code-execution

EXPOSE 8081

CMD ["./worker"]
