FROM golang:1.23-alpine AS builder

RUN apk add --no-cache git postgresql-client

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

RUN go get github.com/stretchr/testify

COPY . .

RUN mkdir -p bin
RUN go build -o bin/import-problems ./cmd/import-problems


CMD ["go", "test", "-v", "-tags=integration", "./tests/..."]
