
services:
  postgres:
    image: postgres:15-alpine
    container_name: contestmanager-postgres
    environment:
      POSTGRES_DB: contestmanager
      POSTGRES_USER: contestmanager
      POSTGRES_PASSWORD: contestmanager_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contestmanager"]
      interval: 0.5s
      timeout: 2s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: contestmanager-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 0.5s
      timeout: 2s
      retries: 3

  contestmanager:
    build: .
    container_name: contestmanager-app
    ports:
      - "50051:50051"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: contestmanager
      DB_PASSWORD: contestmanager_password
      DB_NAME: contestmanager
      DB_SSLMODE: disable
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      GRPC_PORT: 50051
      HTTP_PORT: 8080
      MAX_CONCURRENT_CONTESTS: 3
      CONTEST_DURATION_SECONDS: 300
      MAX_TOKENS_PER_CONTEST: 200000
      LOG_LEVEL: info
      GORM_LOG_LEVEL: error
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  import-problems:
    build: .
    container_name: contestmanager-import-problems
    command: ["./import-problems", "/data/coffee"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: contestmanager
      DB_PASSWORD: contestmanager_password
      DB_NAME: contestmanager
      DB_SSLMODE: disable
    volumes:
      - ./data:/data
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    profiles:
      - import

  delete-problem:
    build: .
    container_name: contestmanager-delete-problem
    command: ["./delete-problem", "Make Them Even"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: contestmanager
      DB_PASSWORD: contestmanager_password
      DB_NAME: contestmanager
      DB_SSLMODE: disable
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    profiles:
      - delete


  worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      LOG_LEVEL: info
      GORM_LOG_LEVEL: error
      WORKER_HEARTBEAT_INTERVAL: 15
      WORKER_JOB_TIMEOUT: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 3

volumes:
  postgres_data:
