# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_manager_pb2 as agent__manager__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAgent = channel.unary_unary(
                '/agentmanager.AgentManagerService/CreateAgent',
                request_serializer=agent__manager__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=agent__manager__pb2.CreateAgentResponse.FromString,
                _registered_method=True)
        self.GetAgentStatus = channel.unary_unary(
                '/agentmanager.AgentManagerService/GetAgentStatus',
                request_serializer=agent__manager__pb2.GetAgentStatusRequest.SerializeToString,
                response_deserializer=agent__manager__pb2.AgentStatusResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/agentmanager.AgentManagerService/ListAgents',
                request_serializer=agent__manager__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=agent__manager__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.StopAgent = channel.unary_unary(
                '/agentmanager.AgentManagerService/StopAgent',
                request_serializer=agent__manager__pb2.StopAgentRequest.SerializeToString,
                response_deserializer=agent__manager__pb2.StopAgentResponse.FromString,
                _registered_method=True)
        self.StreamAgentEvents = channel.unary_stream(
                '/agentmanager.AgentManagerService/StreamAgentEvents',
                request_serializer=agent__manager__pb2.StreamAgentEventsRequest.SerializeToString,
                response_deserializer=agent__manager__pb2.AgentEvent.FromString,
                _registered_method=True)
        self.StreamAgentStatus = channel.unary_stream(
                '/agentmanager.AgentManagerService/StreamAgentStatus',
                request_serializer=agent__manager__pb2.StreamAgentStatusRequest.SerializeToString,
                response_deserializer=agent__manager__pb2.AgentStatusUpdate.FromString,
                _registered_method=True)


class AgentManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAgentEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAgentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=agent__manager__pb2.CreateAgentRequest.FromString,
                    response_serializer=agent__manager__pb2.CreateAgentResponse.SerializeToString,
            ),
            'GetAgentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentStatus,
                    request_deserializer=agent__manager__pb2.GetAgentStatusRequest.FromString,
                    response_serializer=agent__manager__pb2.AgentStatusResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=agent__manager__pb2.ListAgentsRequest.FromString,
                    response_serializer=agent__manager__pb2.ListAgentsResponse.SerializeToString,
            ),
            'StopAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAgent,
                    request_deserializer=agent__manager__pb2.StopAgentRequest.FromString,
                    response_serializer=agent__manager__pb2.StopAgentResponse.SerializeToString,
            ),
            'StreamAgentEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAgentEvents,
                    request_deserializer=agent__manager__pb2.StreamAgentEventsRequest.FromString,
                    response_serializer=agent__manager__pb2.AgentEvent.SerializeToString,
            ),
            'StreamAgentStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAgentStatus,
                    request_deserializer=agent__manager__pb2.StreamAgentStatusRequest.FromString,
                    response_serializer=agent__manager__pb2.AgentStatusUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentmanager.AgentManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentmanager.AgentManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmanager.AgentManagerService/CreateAgent',
            agent__manager__pb2.CreateAgentRequest.SerializeToString,
            agent__manager__pb2.CreateAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmanager.AgentManagerService/GetAgentStatus',
            agent__manager__pb2.GetAgentStatusRequest.SerializeToString,
            agent__manager__pb2.AgentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmanager.AgentManagerService/ListAgents',
            agent__manager__pb2.ListAgentsRequest.SerializeToString,
            agent__manager__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmanager.AgentManagerService/StopAgent',
            agent__manager__pb2.StopAgentRequest.SerializeToString,
            agent__manager__pb2.StopAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAgentEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agentmanager.AgentManagerService/StreamAgentEvents',
            agent__manager__pb2.StreamAgentEventsRequest.SerializeToString,
            agent__manager__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAgentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agentmanager.AgentManagerService/StreamAgentStatus',
            agent__manager__pb2.StreamAgentStatusRequest.SerializeToString,
            agent__manager__pb2.AgentStatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
