// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: contest.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_LANGUAGE_UNSPECIFIED Language = 0
	Language_LANGUAGE_CPP         Language = 1
	Language_LANGUAGE_PYTHON      Language = 2
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "LANGUAGE_UNSPECIFIED",
		1: "LANGUAGE_CPP",
		2: "LANGUAGE_PYTHON",
	}
	Language_value = map[string]int32{
		"LANGUAGE_UNSPECIFIED": 0,
		"LANGUAGE_CPP":         1,
		"LANGUAGE_PYTHON":      2,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_contest_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_contest_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{0}
}

type ContestState int32

const (
	ContestState_CONTEST_STATE_UNSPECIFIED ContestState = 0
	ContestState_CONTEST_STATE_RUNNING     ContestState = 1
	ContestState_CONTEST_STATE_FINISHED    ContestState = 2
)

// Enum value maps for ContestState.
var (
	ContestState_name = map[int32]string{
		0: "CONTEST_STATE_UNSPECIFIED",
		1: "CONTEST_STATE_RUNNING",
		2: "CONTEST_STATE_FINISHED",
	}
	ContestState_value = map[string]int32{
		"CONTEST_STATE_UNSPECIFIED": 0,
		"CONTEST_STATE_RUNNING":     1,
		"CONTEST_STATE_FINISHED":    2,
	}
)

func (x ContestState) Enum() *ContestState {
	p := new(ContestState)
	*p = x
	return p
}

func (x ContestState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContestState) Descriptor() protoreflect.EnumDescriptor {
	return file_contest_proto_enumTypes[1].Descriptor()
}

func (ContestState) Type() protoreflect.EnumType {
	return &file_contest_proto_enumTypes[1]
}

func (x ContestState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContestState.Descriptor instead.
func (ContestState) EnumDescriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{1}
}

type SubmissionStatus int32

const (
	SubmissionStatus_SUBMISSION_STATUS_UNSPECIFIED           SubmissionStatus = 0
	SubmissionStatus_SUBMISSION_STATUS_PENDING               SubmissionStatus = 1
	SubmissionStatus_SUBMISSION_STATUS_COMPILING             SubmissionStatus = 2
	SubmissionStatus_SUBMISSION_STATUS_RUNNING               SubmissionStatus = 3
	SubmissionStatus_SUBMISSION_STATUS_ACCEPTED              SubmissionStatus = 4
	SubmissionStatus_SUBMISSION_STATUS_WRONG_ANSWER          SubmissionStatus = 5
	SubmissionStatus_SUBMISSION_STATUS_PRESENTATION_ERROR    SubmissionStatus = 6
	SubmissionStatus_SUBMISSION_STATUS_TIME_LIMIT_EXCEEDED   SubmissionStatus = 7
	SubmissionStatus_SUBMISSION_STATUS_MEMORY_LIMIT_EXCEEDED SubmissionStatus = 8
	SubmissionStatus_SUBMISSION_STATUS_RUNTIME_ERROR         SubmissionStatus = 9
	SubmissionStatus_SUBMISSION_STATUS_COMPILATION_ERROR     SubmissionStatus = 10
	SubmissionStatus_SUBMISSION_STATUS_OUTPUT_LIMIT_EXCEEDED SubmissionStatus = 11
	SubmissionStatus_SUBMISSION_STATUS_JUDGEMENT_FAILED      SubmissionStatus = 12
)

// Enum value maps for SubmissionStatus.
var (
	SubmissionStatus_name = map[int32]string{
		0:  "SUBMISSION_STATUS_UNSPECIFIED",
		1:  "SUBMISSION_STATUS_PENDING",
		2:  "SUBMISSION_STATUS_COMPILING",
		3:  "SUBMISSION_STATUS_RUNNING",
		4:  "SUBMISSION_STATUS_ACCEPTED",
		5:  "SUBMISSION_STATUS_WRONG_ANSWER",
		6:  "SUBMISSION_STATUS_PRESENTATION_ERROR",
		7:  "SUBMISSION_STATUS_TIME_LIMIT_EXCEEDED",
		8:  "SUBMISSION_STATUS_MEMORY_LIMIT_EXCEEDED",
		9:  "SUBMISSION_STATUS_RUNTIME_ERROR",
		10: "SUBMISSION_STATUS_COMPILATION_ERROR",
		11: "SUBMISSION_STATUS_OUTPUT_LIMIT_EXCEEDED",
		12: "SUBMISSION_STATUS_JUDGEMENT_FAILED",
	}
	SubmissionStatus_value = map[string]int32{
		"SUBMISSION_STATUS_UNSPECIFIED":           0,
		"SUBMISSION_STATUS_PENDING":               1,
		"SUBMISSION_STATUS_COMPILING":             2,
		"SUBMISSION_STATUS_RUNNING":               3,
		"SUBMISSION_STATUS_ACCEPTED":              4,
		"SUBMISSION_STATUS_WRONG_ANSWER":          5,
		"SUBMISSION_STATUS_PRESENTATION_ERROR":    6,
		"SUBMISSION_STATUS_TIME_LIMIT_EXCEEDED":   7,
		"SUBMISSION_STATUS_MEMORY_LIMIT_EXCEEDED": 8,
		"SUBMISSION_STATUS_RUNTIME_ERROR":         9,
		"SUBMISSION_STATUS_COMPILATION_ERROR":     10,
		"SUBMISSION_STATUS_OUTPUT_LIMIT_EXCEEDED": 11,
		"SUBMISSION_STATUS_JUDGEMENT_FAILED":      12,
	}
)

func (x SubmissionStatus) Enum() *SubmissionStatus {
	p := new(SubmissionStatus)
	*p = x
	return p
}

func (x SubmissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contest_proto_enumTypes[2].Descriptor()
}

func (SubmissionStatus) Type() protoreflect.EnumType {
	return &file_contest_proto_enumTypes[2]
}

func (x SubmissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubmissionStatus.Descriptor instead.
func (SubmissionStatus) EnumDescriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{2}
}

type ProblemTag int32

const (
	ProblemTag_PROBLEM_TAG_UNSPECIFIED         ProblemTag = 0
	ProblemTag_PROBLEM_TAG_STRINGS             ProblemTag = 1
	ProblemTag_PROBLEM_TAG_GEOMETRY            ProblemTag = 2
	ProblemTag_PROBLEM_TAG_DYNAMIC_PROGRAMMING ProblemTag = 3
	ProblemTag_PROBLEM_TAG_GRAPHS              ProblemTag = 4
	ProblemTag_PROBLEM_TAG_GREEDY              ProblemTag = 5
	ProblemTag_PROBLEM_TAG_MATH                ProblemTag = 6
	ProblemTag_PROBLEM_TAG_DATA_STRUCTURES     ProblemTag = 7
	ProblemTag_PROBLEM_TAG_SORTING             ProblemTag = 8
	ProblemTag_PROBLEM_TAG_BINARY_SEARCH       ProblemTag = 9
	ProblemTag_PROBLEM_TAG_TWO_POINTERS        ProblemTag = 10
	ProblemTag_PROBLEM_TAG_SLIDING_WINDOW      ProblemTag = 11
	ProblemTag_PROBLEM_TAG_BACKTRACKING        ProblemTag = 12
	ProblemTag_PROBLEM_TAG_BIT_MANIPULATION    ProblemTag = 13
	ProblemTag_PROBLEM_TAG_TREE                ProblemTag = 14
	ProblemTag_PROBLEM_TAG_HEAP                ProblemTag = 15
	ProblemTag_PROBLEM_TAG_STACK               ProblemTag = 16
	ProblemTag_PROBLEM_TAG_QUEUE               ProblemTag = 17
	ProblemTag_PROBLEM_TAG_HASH_TABLE          ProblemTag = 18
	ProblemTag_PROBLEM_TAG_ARRAY               ProblemTag = 19
	ProblemTag_PROBLEM_TAG_LINKED_LIST         ProblemTag = 20
	ProblemTag_PROBLEM_TAG_RECURSION           ProblemTag = 21
	ProblemTag_PROBLEM_TAG_DIVIDE_AND_CONQUER  ProblemTag = 22
	ProblemTag_PROBLEM_TAG_SIMULATION          ProblemTag = 23
	ProblemTag_PROBLEM_TAG_IMPLEMENTATION      ProblemTag = 24
	ProblemTag_PROBLEM_TAG_BRUTE_FORCE         ProblemTag = 25
)

// Enum value maps for ProblemTag.
var (
	ProblemTag_name = map[int32]string{
		0:  "PROBLEM_TAG_UNSPECIFIED",
		1:  "PROBLEM_TAG_STRINGS",
		2:  "PROBLEM_TAG_GEOMETRY",
		3:  "PROBLEM_TAG_DYNAMIC_PROGRAMMING",
		4:  "PROBLEM_TAG_GRAPHS",
		5:  "PROBLEM_TAG_GREEDY",
		6:  "PROBLEM_TAG_MATH",
		7:  "PROBLEM_TAG_DATA_STRUCTURES",
		8:  "PROBLEM_TAG_SORTING",
		9:  "PROBLEM_TAG_BINARY_SEARCH",
		10: "PROBLEM_TAG_TWO_POINTERS",
		11: "PROBLEM_TAG_SLIDING_WINDOW",
		12: "PROBLEM_TAG_BACKTRACKING",
		13: "PROBLEM_TAG_BIT_MANIPULATION",
		14: "PROBLEM_TAG_TREE",
		15: "PROBLEM_TAG_HEAP",
		16: "PROBLEM_TAG_STACK",
		17: "PROBLEM_TAG_QUEUE",
		18: "PROBLEM_TAG_HASH_TABLE",
		19: "PROBLEM_TAG_ARRAY",
		20: "PROBLEM_TAG_LINKED_LIST",
		21: "PROBLEM_TAG_RECURSION",
		22: "PROBLEM_TAG_DIVIDE_AND_CONQUER",
		23: "PROBLEM_TAG_SIMULATION",
		24: "PROBLEM_TAG_IMPLEMENTATION",
		25: "PROBLEM_TAG_BRUTE_FORCE",
	}
	ProblemTag_value = map[string]int32{
		"PROBLEM_TAG_UNSPECIFIED":         0,
		"PROBLEM_TAG_STRINGS":             1,
		"PROBLEM_TAG_GEOMETRY":            2,
		"PROBLEM_TAG_DYNAMIC_PROGRAMMING": 3,
		"PROBLEM_TAG_GRAPHS":              4,
		"PROBLEM_TAG_GREEDY":              5,
		"PROBLEM_TAG_MATH":                6,
		"PROBLEM_TAG_DATA_STRUCTURES":     7,
		"PROBLEM_TAG_SORTING":             8,
		"PROBLEM_TAG_BINARY_SEARCH":       9,
		"PROBLEM_TAG_TWO_POINTERS":        10,
		"PROBLEM_TAG_SLIDING_WINDOW":      11,
		"PROBLEM_TAG_BACKTRACKING":        12,
		"PROBLEM_TAG_BIT_MANIPULATION":    13,
		"PROBLEM_TAG_TREE":                14,
		"PROBLEM_TAG_HEAP":                15,
		"PROBLEM_TAG_STACK":               16,
		"PROBLEM_TAG_QUEUE":               17,
		"PROBLEM_TAG_HASH_TABLE":          18,
		"PROBLEM_TAG_ARRAY":               19,
		"PROBLEM_TAG_LINKED_LIST":         20,
		"PROBLEM_TAG_RECURSION":           21,
		"PROBLEM_TAG_DIVIDE_AND_CONQUER":  22,
		"PROBLEM_TAG_SIMULATION":          23,
		"PROBLEM_TAG_IMPLEMENTATION":      24,
		"PROBLEM_TAG_BRUTE_FORCE":         25,
	}
)

func (x ProblemTag) Enum() *ProblemTag {
	p := new(ProblemTag)
	*p = x
	return p
}

func (x ProblemTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProblemTag) Descriptor() protoreflect.EnumDescriptor {
	return file_contest_proto_enumTypes[3].Descriptor()
}

func (ProblemTag) Type() protoreflect.EnumType {
	return &file_contest_proto_enumTypes[3]
}

func (x ProblemTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProblemTag.Descriptor instead.
func (ProblemTag) EnumDescriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{3}
}

type ProblemStatus int32

const (
	ProblemStatus_PROBLEM_STATUS_UNSPECIFIED ProblemStatus = 0
	ProblemStatus_PROBLEM_STATUS_ACCEPTED    ProblemStatus = 1
	ProblemStatus_PROBLEM_STATUS_TRIED       ProblemStatus = 2
	ProblemStatus_PROBLEM_STATUS_NON_TRIED   ProblemStatus = 3
)

// Enum value maps for ProblemStatus.
var (
	ProblemStatus_name = map[int32]string{
		0: "PROBLEM_STATUS_UNSPECIFIED",
		1: "PROBLEM_STATUS_ACCEPTED",
		2: "PROBLEM_STATUS_TRIED",
		3: "PROBLEM_STATUS_NON_TRIED",
	}
	ProblemStatus_value = map[string]int32{
		"PROBLEM_STATUS_UNSPECIFIED": 0,
		"PROBLEM_STATUS_ACCEPTED":    1,
		"PROBLEM_STATUS_TRIED":       2,
		"PROBLEM_STATUS_NON_TRIED":   3,
	}
)

func (x ProblemStatus) Enum() *ProblemStatus {
	p := new(ProblemStatus)
	*p = x
	return p
}

func (x ProblemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProblemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contest_proto_enumTypes[4].Descriptor()
}

func (ProblemStatus) Type() protoreflect.EnumType {
	return &file_contest_proto_enumTypes[4]
}

func (x ProblemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProblemStatus.Descriptor instead.
func (ProblemStatus) EnumDescriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{4}
}

type Problem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TimeLimitMs   int32                  `protobuf:"varint,4,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	MemoryLimitMb int32                  `protobuf:"varint,5,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	Tag           ProblemTag             `protobuf:"varint,6,opt,name=tag,proto3,enum=contestmanager.ProblemTag" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_contest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{0}
}

func (x *Problem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Problem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Problem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Problem) GetTimeLimitMs() int32 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *Problem) GetMemoryLimitMb() int32 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *Problem) GetTag() ProblemTag {
	if x != nil {
		return x.Tag
	}
	return ProblemTag_PROBLEM_TAG_UNSPECIFIED
}

type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Result        *ParticipantResult     `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_contest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{1}
}

func (x *Participant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Participant) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *Participant) GetResult() *ParticipantResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ProblemResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         ProblemStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=contestmanager.ProblemStatus" json:"status,omitempty"`
	PenaltyCount   int32                  `protobuf:"varint,2,opt,name=penalty_count,json=penaltyCount,proto3" json:"penalty_count,omitempty"`
	PenaltySeconds int32                  `protobuf:"varint,3,opt,name=penalty_seconds,json=penaltySeconds,proto3" json:"penalty_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProblemResult) Reset() {
	*x = ProblemResult{}
	mi := &file_contest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemResult) ProtoMessage() {}

func (x *ProblemResult) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemResult.ProtoReflect.Descriptor instead.
func (*ProblemResult) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{2}
}

func (x *ProblemResult) GetStatus() ProblemStatus {
	if x != nil {
		return x.Status
	}
	return ProblemStatus_PROBLEM_STATUS_UNSPECIFIED
}

func (x *ProblemResult) GetPenaltyCount() int32 {
	if x != nil {
		return x.PenaltyCount
	}
	return 0
}

func (x *ProblemResult) GetPenaltySeconds() int32 {
	if x != nil {
		return x.PenaltySeconds
	}
	return 0
}

type ParticipantResult struct {
	state               protoimpl.MessageState    `protogen:"open.v1"`
	Solved              int32                     `protobuf:"varint,1,opt,name=solved,proto3" json:"solved,omitempty"`
	TotalPenaltySeconds int32                     `protobuf:"varint,2,opt,name=total_penalty_seconds,json=totalPenaltySeconds,proto3" json:"total_penalty_seconds,omitempty"`
	ProblemResults      map[string]*ProblemResult `protobuf:"bytes,3,rep,name=problem_results,json=problemResults,proto3" json:"problem_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Rank                int32                     `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ParticipantResult) Reset() {
	*x = ParticipantResult{}
	mi := &file_contest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantResult) ProtoMessage() {}

func (x *ParticipantResult) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantResult.ProtoReflect.Descriptor instead.
func (*ParticipantResult) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{3}
}

func (x *ParticipantResult) GetSolved() int32 {
	if x != nil {
		return x.Solved
	}
	return 0
}

func (x *ParticipantResult) GetTotalPenaltySeconds() int32 {
	if x != nil {
		return x.TotalPenaltySeconds
	}
	return 0
}

func (x *ParticipantResult) GetProblemResults() map[string]*ProblemResult {
	if x != nil {
		return x.ProblemResults
	}
	return nil
}

func (x *ParticipantResult) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type Contest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         ContestState           `protobuf:"varint,2,opt,name=state,proto3,enum=contestmanager.ContestState" json:"state,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Problems      []*Problem             `protobuf:"bytes,5,rep,name=problems,proto3" json:"problems,omitempty"`
	Participants  []*Participant         `protobuf:"bytes,6,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contest) Reset() {
	*x = Contest{}
	mi := &file_contest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contest) ProtoMessage() {}

func (x *Contest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contest.ProtoReflect.Descriptor instead.
func (*Contest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{4}
}

func (x *Contest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contest) GetState() ContestState {
	if x != nil {
		return x.State
	}
	return ContestState_CONTEST_STATE_UNSPECIFIED
}

func (x *Contest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Contest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *Contest) GetProblems() []*Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

func (x *Contest) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

type Submission struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContestId          string                 `protobuf:"bytes,2,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	ParticipantId      string                 `protobuf:"bytes,3,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	ProblemId          string                 `protobuf:"bytes,4,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Code               string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Language           Language               `protobuf:"varint,6,opt,name=language,proto3,enum=contestmanager.Language" json:"language,omitempty"`
	Status             SubmissionStatus       `protobuf:"varint,7,opt,name=status,proto3,enum=contestmanager.SubmissionStatus" json:"status,omitempty"`
	SubmittedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	VerdictMessage     string                 `protobuf:"bytes,9,opt,name=verdict_message,json=verdictMessage,proto3" json:"verdict_message,omitempty"`
	TotalTestCases     int32                  `protobuf:"varint,10,opt,name=total_test_cases,json=totalTestCases,proto3" json:"total_test_cases,omitempty"`
	ProcessedTestCases int32                  `protobuf:"varint,11,opt,name=processed_test_cases,json=processedTestCases,proto3" json:"processed_test_cases,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_contest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{5}
}

func (x *Submission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Submission) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *Submission) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *Submission) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *Submission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Submission) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *Submission) GetStatus() SubmissionStatus {
	if x != nil {
		return x.Status
	}
	return SubmissionStatus_SUBMISSION_STATUS_UNSPECIFIED
}

func (x *Submission) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Submission) GetVerdictMessage() string {
	if x != nil {
		return x.VerdictMessage
	}
	return ""
}

func (x *Submission) GetTotalTestCases() int32 {
	if x != nil {
		return x.TotalTestCases
	}
	return 0
}

func (x *Submission) GetProcessedTestCases() int32 {
	if x != nil {
		return x.ProcessedTestCases
	}
	return 0
}

type CreateContestRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NumProblems       int32                  `protobuf:"varint,1,opt,name=num_problems,json=numProblems,proto3" json:"num_problems,omitempty"`
	ParticipantModels []string               `protobuf:"bytes,2,rep,name=participant_models,json=participantModels,proto3" json:"participant_models,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateContestRequest) Reset() {
	*x = CreateContestRequest{}
	mi := &file_contest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContestRequest) ProtoMessage() {}

func (x *CreateContestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContestRequest.ProtoReflect.Descriptor instead.
func (*CreateContestRequest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{6}
}

func (x *CreateContestRequest) GetNumProblems() int32 {
	if x != nil {
		return x.NumProblems
	}
	return 0
}

func (x *CreateContestRequest) GetParticipantModels() []string {
	if x != nil {
		return x.ParticipantModels
	}
	return nil
}

type CreateContestWithProblemsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProblemIds        []string               `protobuf:"bytes,1,rep,name=problem_ids,json=problemIds,proto3" json:"problem_ids,omitempty"`
	ParticipantModels []string               `protobuf:"bytes,2,rep,name=participant_models,json=participantModels,proto3" json:"participant_models,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateContestWithProblemsRequest) Reset() {
	*x = CreateContestWithProblemsRequest{}
	mi := &file_contest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContestWithProblemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContestWithProblemsRequest) ProtoMessage() {}

func (x *CreateContestWithProblemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContestWithProblemsRequest.ProtoReflect.Descriptor instead.
func (*CreateContestWithProblemsRequest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{7}
}

func (x *CreateContestWithProblemsRequest) GetProblemIds() []string {
	if x != nil {
		return x.ProblemIds
	}
	return nil
}

func (x *CreateContestWithProblemsRequest) GetParticipantModels() []string {
	if x != nil {
		return x.ParticipantModels
	}
	return nil
}

type CreateContestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Contest       *Contest               `protobuf:"bytes,2,opt,name=contest,proto3" json:"contest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContestResponse) Reset() {
	*x = CreateContestResponse{}
	mi := &file_contest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContestResponse) ProtoMessage() {}

func (x *CreateContestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContestResponse.ProtoReflect.Descriptor instead.
func (*CreateContestResponse) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{8}
}

func (x *CreateContestResponse) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *CreateContestResponse) GetContest() *Contest {
	if x != nil {
		return x.Contest
	}
	return nil
}

type GetContestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContestRequest) Reset() {
	*x = GetContestRequest{}
	mi := &file_contest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContestRequest) ProtoMessage() {}

func (x *GetContestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContestRequest.ProtoReflect.Descriptor instead.
func (*GetContestRequest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{9}
}

func (x *GetContestRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

type GetContestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contest       *Contest               `protobuf:"bytes,1,opt,name=contest,proto3" json:"contest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContestResponse) Reset() {
	*x = GetContestResponse{}
	mi := &file_contest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContestResponse) ProtoMessage() {}

func (x *GetContestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContestResponse.ProtoReflect.Descriptor instead.
func (*GetContestResponse) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{10}
}

func (x *GetContestResponse) GetContest() *Contest {
	if x != nil {
		return x.Contest
	}
	return nil
}

type ListContestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContestsRequest) Reset() {
	*x = ListContestsRequest{}
	mi := &file_contest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContestsRequest) ProtoMessage() {}

func (x *ListContestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContestsRequest.ProtoReflect.Descriptor instead.
func (*ListContestsRequest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{11}
}

func (x *ListContestsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListContestsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListContestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contests      []*Contest             `protobuf:"bytes,1,rep,name=contests,proto3" json:"contests,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContestsResponse) Reset() {
	*x = ListContestsResponse{}
	mi := &file_contest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContestsResponse) ProtoMessage() {}

func (x *ListContestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContestsResponse.ProtoReflect.Descriptor instead.
func (*ListContestsResponse) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{12}
}

func (x *ListContestsResponse) GetContests() []*Contest {
	if x != nil {
		return x.Contests
	}
	return nil
}

func (x *ListContestsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SubmitSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	ProblemId     string                 `protobuf:"bytes,3,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Language      Language               `protobuf:"varint,5,opt,name=language,proto3,enum=contestmanager.Language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSolutionRequest) Reset() {
	*x = SubmitSolutionRequest{}
	mi := &file_contest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSolutionRequest) ProtoMessage() {}

func (x *SubmitSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSolutionRequest.ProtoReflect.Descriptor instead.
func (*SubmitSolutionRequest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitSolutionRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *SubmitSolutionRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *SubmitSolutionRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *SubmitSolutionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SubmitSolutionRequest) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

type SubmitSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Submission    *Submission            `protobuf:"bytes,2,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSolutionResponse) Reset() {
	*x = SubmitSolutionResponse{}
	mi := &file_contest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSolutionResponse) ProtoMessage() {}

func (x *SubmitSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSolutionResponse.ProtoReflect.Descriptor instead.
func (*SubmitSolutionResponse) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitSolutionResponse) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *SubmitSolutionResponse) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type GetSubmissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	ProblemId     string                 `protobuf:"bytes,3,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionsRequest) Reset() {
	*x = GetSubmissionsRequest{}
	mi := &file_contest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionsRequest) ProtoMessage() {}

func (x *GetSubmissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubmissionsRequest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{15}
}

func (x *GetSubmissionsRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *GetSubmissionsRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *GetSubmissionsRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

type GetSubmissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submissions   []*Submission          `protobuf:"bytes,1,rep,name=submissions,proto3" json:"submissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionsResponse) Reset() {
	*x = GetSubmissionsResponse{}
	mi := &file_contest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionsResponse) ProtoMessage() {}

func (x *GetSubmissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubmissionsResponse) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{16}
}

func (x *GetSubmissionsResponse) GetSubmissions() []*Submission {
	if x != nil {
		return x.Submissions
	}
	return nil
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_contest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{17}
}

func (x *GetLeaderboardRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*Participant         `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_contest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{18}
}

func (x *GetLeaderboardResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *GetLeaderboardResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StreamLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLeaderboardRequest) Reset() {
	*x = StreamLeaderboardRequest{}
	mi := &file_contest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLeaderboardRequest) ProtoMessage() {}

func (x *StreamLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*StreamLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{19}
}

func (x *StreamLeaderboardRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

type LeaderboardUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*Participant         `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardUpdate) Reset() {
	*x = LeaderboardUpdate{}
	mi := &file_contest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardUpdate) ProtoMessage() {}

func (x *LeaderboardUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardUpdate.ProtoReflect.Descriptor instead.
func (*LeaderboardUpdate) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{20}
}

func (x *LeaderboardUpdate) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *LeaderboardUpdate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_contest_proto protoreflect.FileDescriptor

const file_contest_proto_rawDesc = "" +
	"\n" +
	"\rcontest.proto\x12\x0econtestmanager\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n" +
	"\aProblem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\rtime_limit_ms\x18\x04 \x01(\x05R\vtimeLimitMs\x12&\n" +
	"\x0fmemory_limit_mb\x18\x05 \x01(\x05R\rmemoryLimitMb\x12,\n" +
	"\x03tag\x18\x06 \x01(\x0e2\x1a.contestmanager.ProblemTagR\x03tag\"w\n" +
	"\vParticipant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x129\n" +
	"\x06result\x18\x03 \x01(\v2!.contestmanager.ParticipantResultR\x06result\"\x94\x01\n" +
	"\rProblemResult\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.contestmanager.ProblemStatusR\x06status\x12#\n" +
	"\rpenalty_count\x18\x02 \x01(\x05R\fpenaltyCount\x12'\n" +
	"\x0fpenalty_seconds\x18\x03 \x01(\x05R\x0epenaltySeconds\"\xb5\x02\n" +
	"\x11ParticipantResult\x12\x16\n" +
	"\x06solved\x18\x01 \x01(\x05R\x06solved\x122\n" +
	"\x15total_penalty_seconds\x18\x02 \x01(\x05R\x13totalPenaltySeconds\x12^\n" +
	"\x0fproblem_results\x18\x03 \x03(\v25.contestmanager.ParticipantResult.ProblemResultsEntryR\x0eproblemResults\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x1a`\n" +
	"\x13ProblemResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.contestmanager.ProblemResultR\x05value:\x028\x01\"\xb3\x02\n" +
	"\aContest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.contestmanager.ContestStateR\x05state\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x123\n" +
	"\aends_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x123\n" +
	"\bproblems\x18\x05 \x03(\v2\x17.contestmanager.ProblemR\bproblems\x12?\n" +
	"\fparticipants\x18\x06 \x03(\v2\x1b.contestmanager.ParticipantR\fparticipants\"\xc9\x03\n" +
	"\n" +
	"Submission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x02 \x01(\tR\tcontestId\x12%\n" +
	"\x0eparticipant_id\x18\x03 \x01(\tR\rparticipantId\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x04 \x01(\tR\tproblemId\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x124\n" +
	"\blanguage\x18\x06 \x01(\x0e2\x18.contestmanager.LanguageR\blanguage\x128\n" +
	"\x06status\x18\a \x01(\x0e2 .contestmanager.SubmissionStatusR\x06status\x12=\n" +
	"\fsubmitted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12'\n" +
	"\x0fverdict_message\x18\t \x01(\tR\x0everdictMessage\x12(\n" +
	"\x10total_test_cases\x18\n" +
	" \x01(\x05R\x0etotalTestCases\x120\n" +
	"\x14processed_test_cases\x18\v \x01(\x05R\x12processedTestCases\"h\n" +
	"\x14CreateContestRequest\x12!\n" +
	"\fnum_problems\x18\x01 \x01(\x05R\vnumProblems\x12-\n" +
	"\x12participant_models\x18\x02 \x03(\tR\x11participantModels\"r\n" +
	" CreateContestWithProblemsRequest\x12\x1f\n" +
	"\vproblem_ids\x18\x01 \x03(\tR\n" +
	"problemIds\x12-\n" +
	"\x12participant_models\x18\x02 \x03(\tR\x11participantModels\"i\n" +
	"\x15CreateContestResponse\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x121\n" +
	"\acontest\x18\x02 \x01(\v2\x17.contestmanager.ContestR\acontest\"2\n" +
	"\x11GetContestRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\"G\n" +
	"\x12GetContestResponse\x121\n" +
	"\acontest\x18\x01 \x01(\v2\x17.contestmanager.ContestR\acontest\"Q\n" +
	"\x13ListContestsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"s\n" +
	"\x14ListContestsResponse\x123\n" +
	"\bcontests\x18\x01 \x03(\v2\x17.contestmanager.ContestR\bcontests\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc6\x01\n" +
	"\x15SubmitSolutionRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x03 \x01(\tR\tproblemId\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x124\n" +
	"\blanguage\x18\x05 \x01(\x0e2\x18.contestmanager.LanguageR\blanguage\"y\n" +
	"\x16SubmitSolutionResponse\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12:\n" +
	"\n" +
	"submission\x18\x02 \x01(\v2\x1a.contestmanager.SubmissionR\n" +
	"submission\"|\n" +
	"\x15GetSubmissionsRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x03 \x01(\tR\tproblemId\"V\n" +
	"\x16GetSubmissionsResponse\x12<\n" +
	"\vsubmissions\x18\x01 \x03(\v2\x1a.contestmanager.SubmissionR\vsubmissions\"6\n" +
	"\x15GetLeaderboardRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\"\x94\x01\n" +
	"\x16GetLeaderboardResponse\x12?\n" +
	"\fparticipants\x18\x01 \x03(\v2\x1b.contestmanager.ParticipantR\fparticipants\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"9\n" +
	"\x18StreamLeaderboardRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\"\x8f\x01\n" +
	"\x11LeaderboardUpdate\x12?\n" +
	"\fparticipants\x18\x01 \x03(\v2\x1b.contestmanager.ParticipantR\fparticipants\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*K\n" +
	"\bLanguage\x12\x18\n" +
	"\x14LANGUAGE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fLANGUAGE_CPP\x10\x01\x12\x13\n" +
	"\x0fLANGUAGE_PYTHON\x10\x02*d\n" +
	"\fContestState\x12\x1d\n" +
	"\x19CONTEST_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONTEST_STATE_RUNNING\x10\x01\x12\x1a\n" +
	"\x16CONTEST_STATE_FINISHED\x10\x02*\xfd\x03\n" +
	"\x10SubmissionStatus\x12!\n" +
	"\x1dSUBMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SUBMISSION_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bSUBMISSION_STATUS_COMPILING\x10\x02\x12\x1d\n" +
	"\x19SUBMISSION_STATUS_RUNNING\x10\x03\x12\x1e\n" +
	"\x1aSUBMISSION_STATUS_ACCEPTED\x10\x04\x12\"\n" +
	"\x1eSUBMISSION_STATUS_WRONG_ANSWER\x10\x05\x12(\n" +
	"$SUBMISSION_STATUS_PRESENTATION_ERROR\x10\x06\x12)\n" +
	"%SUBMISSION_STATUS_TIME_LIMIT_EXCEEDED\x10\a\x12+\n" +
	"'SUBMISSION_STATUS_MEMORY_LIMIT_EXCEEDED\x10\b\x12#\n" +
	"\x1fSUBMISSION_STATUS_RUNTIME_ERROR\x10\t\x12'\n" +
	"#SUBMISSION_STATUS_COMPILATION_ERROR\x10\n" +
	"\x12+\n" +
	"'SUBMISSION_STATUS_OUTPUT_LIMIT_EXCEEDED\x10\v\x12&\n" +
	"\"SUBMISSION_STATUS_JUDGEMENT_FAILED\x10\f*\xe0\x05\n" +
	"\n" +
	"ProblemTag\x12\x1b\n" +
	"\x17PROBLEM_TAG_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PROBLEM_TAG_STRINGS\x10\x01\x12\x18\n" +
	"\x14PROBLEM_TAG_GEOMETRY\x10\x02\x12#\n" +
	"\x1fPROBLEM_TAG_DYNAMIC_PROGRAMMING\x10\x03\x12\x16\n" +
	"\x12PROBLEM_TAG_GRAPHS\x10\x04\x12\x16\n" +
	"\x12PROBLEM_TAG_GREEDY\x10\x05\x12\x14\n" +
	"\x10PROBLEM_TAG_MATH\x10\x06\x12\x1f\n" +
	"\x1bPROBLEM_TAG_DATA_STRUCTURES\x10\a\x12\x17\n" +
	"\x13PROBLEM_TAG_SORTING\x10\b\x12\x1d\n" +
	"\x19PROBLEM_TAG_BINARY_SEARCH\x10\t\x12\x1c\n" +
	"\x18PROBLEM_TAG_TWO_POINTERS\x10\n" +
	"\x12\x1e\n" +
	"\x1aPROBLEM_TAG_SLIDING_WINDOW\x10\v\x12\x1c\n" +
	"\x18PROBLEM_TAG_BACKTRACKING\x10\f\x12 \n" +
	"\x1cPROBLEM_TAG_BIT_MANIPULATION\x10\r\x12\x14\n" +
	"\x10PROBLEM_TAG_TREE\x10\x0e\x12\x14\n" +
	"\x10PROBLEM_TAG_HEAP\x10\x0f\x12\x15\n" +
	"\x11PROBLEM_TAG_STACK\x10\x10\x12\x15\n" +
	"\x11PROBLEM_TAG_QUEUE\x10\x11\x12\x1a\n" +
	"\x16PROBLEM_TAG_HASH_TABLE\x10\x12\x12\x15\n" +
	"\x11PROBLEM_TAG_ARRAY\x10\x13\x12\x1b\n" +
	"\x17PROBLEM_TAG_LINKED_LIST\x10\x14\x12\x19\n" +
	"\x15PROBLEM_TAG_RECURSION\x10\x15\x12\"\n" +
	"\x1ePROBLEM_TAG_DIVIDE_AND_CONQUER\x10\x16\x12\x1a\n" +
	"\x16PROBLEM_TAG_SIMULATION\x10\x17\x12\x1e\n" +
	"\x1aPROBLEM_TAG_IMPLEMENTATION\x10\x18\x12\x1b\n" +
	"\x17PROBLEM_TAG_BRUTE_FORCE\x10\x19*\x84\x01\n" +
	"\rProblemStatus\x12\x1e\n" +
	"\x1aPROBLEM_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROBLEM_STATUS_ACCEPTED\x10\x01\x12\x18\n" +
	"\x14PROBLEM_STATUS_TRIED\x10\x02\x12\x1c\n" +
	"\x18PROBLEM_STATUS_NON_TRIED\x10\x032\x9b\x06\n" +
	"\x0eContestService\x12\\\n" +
	"\rCreateContest\x12$.contestmanager.CreateContestRequest\x1a%.contestmanager.CreateContestResponse\x12t\n" +
	"\x19CreateContestWithProblems\x120.contestmanager.CreateContestWithProblemsRequest\x1a%.contestmanager.CreateContestResponse\x12S\n" +
	"\n" +
	"GetContest\x12!.contestmanager.GetContestRequest\x1a\".contestmanager.GetContestResponse\x12Y\n" +
	"\fListContests\x12#.contestmanager.ListContestsRequest\x1a$.contestmanager.ListContestsResponse\x12_\n" +
	"\x0eSubmitSolution\x12%.contestmanager.SubmitSolutionRequest\x1a&.contestmanager.SubmitSolutionResponse\x12_\n" +
	"\x0eGetSubmissions\x12%.contestmanager.GetSubmissionsRequest\x1a&.contestmanager.GetSubmissionsResponse\x12_\n" +
	"\x0eGetLeaderboard\x12%.contestmanager.GetLeaderboardRequest\x1a&.contestmanager.GetLeaderboardResponse\x12b\n" +
	"\x11StreamLeaderboard\x12(.contestmanager.StreamLeaderboardRequest\x1a!.contestmanager.LeaderboardUpdate0\x01B\x19Z\x17contestmanager/api/grpcb\x06proto3"

var (
	file_contest_proto_rawDescOnce sync.Once
	file_contest_proto_rawDescData []byte
)

func file_contest_proto_rawDescGZIP() []byte {
	file_contest_proto_rawDescOnce.Do(func() {
		file_contest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contest_proto_rawDesc), len(file_contest_proto_rawDesc)))
	})
	return file_contest_proto_rawDescData
}

var file_contest_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_contest_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_contest_proto_goTypes = []any{
	(Language)(0),                            // 0: contestmanager.Language
	(ContestState)(0),                        // 1: contestmanager.ContestState
	(SubmissionStatus)(0),                    // 2: contestmanager.SubmissionStatus
	(ProblemTag)(0),                          // 3: contestmanager.ProblemTag
	(ProblemStatus)(0),                       // 4: contestmanager.ProblemStatus
	(*Problem)(nil),                          // 5: contestmanager.Problem
	(*Participant)(nil),                      // 6: contestmanager.Participant
	(*ProblemResult)(nil),                    // 7: contestmanager.ProblemResult
	(*ParticipantResult)(nil),                // 8: contestmanager.ParticipantResult
	(*Contest)(nil),                          // 9: contestmanager.Contest
	(*Submission)(nil),                       // 10: contestmanager.Submission
	(*CreateContestRequest)(nil),             // 11: contestmanager.CreateContestRequest
	(*CreateContestWithProblemsRequest)(nil), // 12: contestmanager.CreateContestWithProblemsRequest
	(*CreateContestResponse)(nil),            // 13: contestmanager.CreateContestResponse
	(*GetContestRequest)(nil),                // 14: contestmanager.GetContestRequest
	(*GetContestResponse)(nil),               // 15: contestmanager.GetContestResponse
	(*ListContestsRequest)(nil),              // 16: contestmanager.ListContestsRequest
	(*ListContestsResponse)(nil),             // 17: contestmanager.ListContestsResponse
	(*SubmitSolutionRequest)(nil),            // 18: contestmanager.SubmitSolutionRequest
	(*SubmitSolutionResponse)(nil),           // 19: contestmanager.SubmitSolutionResponse
	(*GetSubmissionsRequest)(nil),            // 20: contestmanager.GetSubmissionsRequest
	(*GetSubmissionsResponse)(nil),           // 21: contestmanager.GetSubmissionsResponse
	(*GetLeaderboardRequest)(nil),            // 22: contestmanager.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil),           // 23: contestmanager.GetLeaderboardResponse
	(*StreamLeaderboardRequest)(nil),         // 24: contestmanager.StreamLeaderboardRequest
	(*LeaderboardUpdate)(nil),                // 25: contestmanager.LeaderboardUpdate
	nil,                                      // 26: contestmanager.ParticipantResult.ProblemResultsEntry
	(*timestamppb.Timestamp)(nil),            // 27: google.protobuf.Timestamp
}
var file_contest_proto_depIdxs = []int32{
	3,  // 0: contestmanager.Problem.tag:type_name -> contestmanager.ProblemTag
	8,  // 1: contestmanager.Participant.result:type_name -> contestmanager.ParticipantResult
	4,  // 2: contestmanager.ProblemResult.status:type_name -> contestmanager.ProblemStatus
	26, // 3: contestmanager.ParticipantResult.problem_results:type_name -> contestmanager.ParticipantResult.ProblemResultsEntry
	1,  // 4: contestmanager.Contest.state:type_name -> contestmanager.ContestState
	27, // 5: contestmanager.Contest.started_at:type_name -> google.protobuf.Timestamp
	27, // 6: contestmanager.Contest.ends_at:type_name -> google.protobuf.Timestamp
	5,  // 7: contestmanager.Contest.problems:type_name -> contestmanager.Problem
	6,  // 8: contestmanager.Contest.participants:type_name -> contestmanager.Participant
	0,  // 9: contestmanager.Submission.language:type_name -> contestmanager.Language
	2,  // 10: contestmanager.Submission.status:type_name -> contestmanager.SubmissionStatus
	27, // 11: contestmanager.Submission.submitted_at:type_name -> google.protobuf.Timestamp
	9,  // 12: contestmanager.CreateContestResponse.contest:type_name -> contestmanager.Contest
	9,  // 13: contestmanager.GetContestResponse.contest:type_name -> contestmanager.Contest
	9,  // 14: contestmanager.ListContestsResponse.contests:type_name -> contestmanager.Contest
	0,  // 15: contestmanager.SubmitSolutionRequest.language:type_name -> contestmanager.Language
	10, // 16: contestmanager.SubmitSolutionResponse.submission:type_name -> contestmanager.Submission
	10, // 17: contestmanager.GetSubmissionsResponse.submissions:type_name -> contestmanager.Submission
	6,  // 18: contestmanager.GetLeaderboardResponse.participants:type_name -> contestmanager.Participant
	27, // 19: contestmanager.GetLeaderboardResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 20: contestmanager.LeaderboardUpdate.participants:type_name -> contestmanager.Participant
	27, // 21: contestmanager.LeaderboardUpdate.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 22: contestmanager.ParticipantResult.ProblemResultsEntry.value:type_name -> contestmanager.ProblemResult
	11, // 23: contestmanager.ContestService.CreateContest:input_type -> contestmanager.CreateContestRequest
	12, // 24: contestmanager.ContestService.CreateContestWithProblems:input_type -> contestmanager.CreateContestWithProblemsRequest
	14, // 25: contestmanager.ContestService.GetContest:input_type -> contestmanager.GetContestRequest
	16, // 26: contestmanager.ContestService.ListContests:input_type -> contestmanager.ListContestsRequest
	18, // 27: contestmanager.ContestService.SubmitSolution:input_type -> contestmanager.SubmitSolutionRequest
	20, // 28: contestmanager.ContestService.GetSubmissions:input_type -> contestmanager.GetSubmissionsRequest
	22, // 29: contestmanager.ContestService.GetLeaderboard:input_type -> contestmanager.GetLeaderboardRequest
	24, // 30: contestmanager.ContestService.StreamLeaderboard:input_type -> contestmanager.StreamLeaderboardRequest
	13, // 31: contestmanager.ContestService.CreateContest:output_type -> contestmanager.CreateContestResponse
	13, // 32: contestmanager.ContestService.CreateContestWithProblems:output_type -> contestmanager.CreateContestResponse
	15, // 33: contestmanager.ContestService.GetContest:output_type -> contestmanager.GetContestResponse
	17, // 34: contestmanager.ContestService.ListContests:output_type -> contestmanager.ListContestsResponse
	19, // 35: contestmanager.ContestService.SubmitSolution:output_type -> contestmanager.SubmitSolutionResponse
	21, // 36: contestmanager.ContestService.GetSubmissions:output_type -> contestmanager.GetSubmissionsResponse
	23, // 37: contestmanager.ContestService.GetLeaderboard:output_type -> contestmanager.GetLeaderboardResponse
	25, // 38: contestmanager.ContestService.StreamLeaderboard:output_type -> contestmanager.LeaderboardUpdate
	31, // [31:39] is the sub-list for method output_type
	23, // [23:31] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_contest_proto_init() }
func file_contest_proto_init() {
	if File_contest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contest_proto_rawDesc), len(file_contest_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contest_proto_goTypes,
		DependencyIndexes: file_contest_proto_depIdxs,
		EnumInfos:         file_contest_proto_enumTypes,
		MessageInfos:      file_contest_proto_msgTypes,
	}.Build()
	File_contest_proto = out.File
	file_contest_proto_goTypes = nil
	file_contest_proto_depIdxs = nil
}
